name: Snake Game

on:
  push:
    branches:
      - main

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Generate Snake SVG
      uses: Platane/snk@master
      with:
        github_user: Rodrigo-HM
        svg_out_path: output/github-contribution-grid-snake.svg

    - name: Commit & Push generated Snake SVG
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add output/github-contribution-grid-snake.svg
        git commit -m "Generate Snake Game SVG"
        git push
